<definitions name = "HelloWorldService"
             targetNamespace = "http://www.foo.bar/HelloWorldService.wsdl"
             xmlns = "http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap = "http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns = "http://www.foo.bar/HelloWorldService.wsdl"
             xmlns:xsd = "http://www.w3.org/2001/XMLSchema">

    <message name = "SayHelloRequest">
        <part name = "firstName" type = "xsd:string"/>
    </message>

    <message name = "SayHelloResponse">
        <part name = "greeting" type = "xsd:string"/>
    </message>

    <portType name = "HelloPortType">
        <operation name = "sayHello">
            <input message = "tns:SayHelloRequest"/>
            <output message = "tns:SayHelloResponse"/>
        </operation>
        <operation name = "sayDynamicHello">
            <input message = "tns:SayHelloRequest"/>
            <output message = "tns:SayHelloResponse"/>
        </operation>
    </portType>

    <binding name = "HelloBinding" type = "tns:HelloPortType">
        <soap:binding style = "rpc" transport = "http://schemas.xmlsoap.org/soap/http"/>
        <operation name = "sayHello">
            <soap:operation soapAction = "sayHello"/>
            <input>
                <soap:body
                        encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"
                        namespace = "urn:hello:helloWorldService"
                        use = "encoded"/>
            </input>

            <output>
                <soap:body
                        encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"
                        namespace = "urn:hello:helloWorldService"
                        use = "encoded"/>
            </output>
        </operation>
        <operation name = "sayDynamicHello">
            <soap:operation soapAction = "sayDynamicHello"/>
            <input>
                <soap:body
                        encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"
                        namespace = "urn:hello:helloWorldService"
                        use = "encoded"/>
            </input>

            <output>
                <soap:body
                        encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"
                        namespace = "urn:hello:helloWorldService"
                        use = "encoded"/>
            </output>
        </operation>
    </binding>

    <service name = "HelloWorldService">
        <documentation>WSDL File for HelloService</documentation>
        <port binding = "tns:HelloBinding" name = "HelloWorldPort">
            <soap:address location = "http://localhost:8001/hello/world" />
        </port>
    </service>
</definitions>
